editor: source

execute:
  cache: false # Do not change!
  freeze: false # Do not change!

project:
  type: website
  output-dir: docs

title: "LogoActions: GitHub Actions for the NetLogo Community ðŸš€"
author: Daniel Vartanian
date: today
date-format: long
keyword: >
  Agent-Based Modeling. Individual Based Modeling. Multi-Agent Systems.
  Automation. CI/CD. Complex Systems. Complexity Science. Computational Modeling.
  Continuous Integration. DevOps. GitHub Actions. High-Performance Computing.
  NetLogo. Netlogo Models. Reproducible Research. Scientific Computing.
  Simulations. Workflow Automation. Test Automation.

website:
  site-url: https://danielvartan.github.io/logoactions/
  repo-url: https://github.com/danielvartan/logoactions/
  issue-url: https://github.com/danielvartan/logoactions/issues/
  repo-branch: main
  repo-actions: [edit, source, issue]
  search: false
  navbar:
    title: false
    right:
      - icon: github
        href: https://github.com/danielvartan/logoactions/
        aria-label: GitHub

format:
  html:
    locale: en
    language: en-us
    code-fold: false
    code-link: true
    df-print: paged
    repo-actions: true
